sudo: false

language: generic
matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.03.0 OPAM_VERSION=1.2.2

    - os: osx
      env: OCAML_VERSION=4.03.0 OPAM_VERSION=1.2.2

addons:
  apt:
    sources:
    - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
      key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - libelf-dev
    - libgmp-dev # for opam's conf-gmp
    - aspcud
    - yarn

before_install: bash -e resources/travis/before_install.sh
install: bash -e resources/travis/install_deps.sh
script: bash -e resources/travis/build.sh
before_deploy: bash -e resources/travis/before_deploy.sh

cache:
  directories:
  - $HOME/.flow_cache
  - $HOME/.yarn-cache
  - node_modules
  - resources/travis/node_modules
  - src/parser/node_modules

before_cache:
  - rm -rf $HOME/.flow_cache/ocaml-*/.opam/log

# deploy:
# upload releases to github, from both Mac and Linux
# - provider: releases
#   api_key:
#     # flow-bot
#     secure: "l3R6GrPhrqUIXlAcknFA7rKllPmVsY/1cOGtctxFQ6++oC3xd+XawIMVAR78ZtUoirZ+/3KYdY6o3SoGMb6olgnSerR/CXktP4DXuUK6XlHGRxqSRCclWra3DnJutlaiafnurhIruRMIvXeTYiO2Q1MU/nyQVKZtOhJJHEBg0Mc="
#   repo: facebook/flow
#   skip_cleanup: true
#   file_glob: true
#   file: flow-*.zip
#   on:
#     tags: true
#     condition:
#     - $OCAML_VERSION = 4.03.0
#     - $OPAM_VERSION = 1.2.2

# Deploy the parser to npm
# - provider: script
#   repo: facebook/flow
#   script: bash -e resources/travis/deploy_npm.sh
#   skip_cleanup: true
#   on:
#     tags: true
#     condition:
#     - $TRAVIS_OS_NAME = linux
#     - $OCAML_VERSION = 4.03.0
#     - $OPAM_VERSION = 1.2.2

# Deploy the website
# - provider: script
#   repo: facebook/flow
#   script: bash -e resources/travis/deploy.sh
#   skip_cleanup: true
#   on:
#     branch: master
#     condition:
#     - $TRAVIS_TAG != "" || $TRAVIS_BRANCH = "master"
#     - $TRAVIS_OS_NAME = linux
#     - $OCAML_VERSION = 4.03.0
#     - $OPAM_VERSION = 1.2.2

# Upload release versions of flow.js
# - provider: s3
#   access_key_id: "$AWS_ACCESS_KEY_ID"
#   secret_access_key: "$AWS_SECRET_ACCESS_KEY"
#   bucket: "$S3_BUCKET"
#   skip_cleanup: true
#   local_dir: "$HOME/static"
#   upload-dir: static
#   on:
#     tags: true
#     condition:
#     - $TRAVIS_OS_NAME = linux
#     - $OCAML_VERSION = 4.03.0
#     - $OPAM_VERSION = 1.2.2

# Deploy to opam
# - provider: script
#   repo: facebook/flow
#   script: bash -e resources/travis/deploy_opam.sh
#   skip_cleanup: true
#   on:
#     tags: true
#     condition:
#     - $TRAVIS_OS_NAME = linux
#     - $OCAML_VERSION = 4.03.0
#     - $OPAM_VERSION = 1.2.2

# The use of secure prevents forks from spamming irc and email.
# See https://github.com/travis-ci/travis-ci/issues/5063
# notifications:
#   email:
#     recipients:
#       # flowtype@fb.com
#       secure: "AWT9H7vKPWp/GYMxKij58cIn7v5ehpm/4ecNqCCDTDVHNEBoP4z6BJdPZyheOQ0QL47m7E5Qy2okbPRhmItZV74Gm38Ri7lvmm6o5vscv428zcmPiZLsob8ibJkYQC5TnUsJigyr8yoCmIXyj9WPw3Tfm96eoZ/vvnoDQGxQPs4="
#   irc:
#     channels:
#       # chat.freenode.net#flowtype
#       secure: "OLvGXInHGV66u17k4JPZJTXZyrlqCeAVjVQ+oZuqV5JQo6lep/GtcU6uwmjJOgY/yQR7FPvBG92ru4ef/6CIkIwbCq3Zt/ftfei8rNFO0FlymdC7YXjB8hqN8zs6FIVyxzkjOyg8mX1tRulGwxOLB4yeua9t91RiCkjHtvXeixw="
#     on_success: change
